name: valgene_cli
description: Valgene (Validation Generator) generates validator and Dto boiler plate code from your OpenAPI specs.
version: 0.0.1
homepage: https://github.com/valgene.dart/valgene.dart-cli
author: Sven Assmann <sven@d34dl0ck.me>

environment:
  sdk: '>=2.0.0 <3.0.0'

# Add the bin/valgene.dart script to the scripts pub installs.
executables:
  valgene:

dependencies:
  yaml: ^2.1.15
  recase: ^2.0.0+1
  mustache: ^1.0.2
  args: ^1.5.0
  logging: ^0.11.3+2
  meta: ^1.1.6

dev_dependencies:
  test: ^1.4.0
  mockito: ^3.0.0